name: Engine Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout Code
        uses: actions/checkout@v3

      - name: 🛠️ Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang gcc python3 python3-pip docker.io
          pip3 install -r requirements.txt

  build-engine:
    name: Build Engine
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: 🛠️ Checkout Code
        uses: actions/checkout@v3

      - name: 🛠️ Build Engine
        run: |
          if [[ $RUNNER_OS == "Windows" ]]; then
            cl /EHsc engine.cpp /Feengine.exe
          else
            g++ -o engine engine.cpp
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build-engine
    steps:
      - name: 🛠️ Checkout Code
        uses: actions/checkout@v3

      - name: 🛠️ Run Unit Tests
        run: |
          ./engine --test

      - name: 🛠️ Run Integration Tests
        run: |
          python3 integration_tests.py
