name: Azure DevOps CLI Installation and Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: 🐇 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐇 Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip curl
          python3 -m pip install azure-cli

  install-azure-devops-cli:
    name: Install/Update Azure DevOps CLI
    runs-on: ubuntu-latest
    steps:
      - name: 🐇 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐇 Install/Update Azure DevOps CLI
        run: |
          chmod +x ./install-azure-devops-cli.sh
          ./install-azure-devops-cli.sh

  validate-installation:
    name: Validate Azure DevOps CLI Installation
    runs-on: ubuntu-latest
    needs: install-azure-devops-cli
    steps:
      - name: 🐇 Verify Azure DevOps CLI Installation
        run: |
          az extension show -n azure-devops
